import React from 'react';
import { Document, Page, Text, View, StyleSheet, Svg, Line, Circle } from '@react-pdf/renderer';
import { familyFor } from './fonts.js';
import { formatCaseNumber } from '../lib/ids.js';

/** Shared PDF chrome: A4 page, Jansah letterhead, prototype footer (§21), tokens from the UI kit. */

export const C = {
  ink: '#23231F', ink2: '#61605A', ink3: '#8B8A82',
  neem: '#0A5C4A', neemDark: '#04322A', neemLight: '#E4F3ED',
  haldi: '#B8770F', haldiLight: '#FBF0DA', haldiDark: '#6B4407',
  gerua: '#C2491F', geruaLight: '#FBEDE6',
  line: '#E3E1D8', paper1: '#F8F7F3',
};

export const s = StyleSheet.create({
  page: {
    paddingTop: 44, paddingBottom: 64, paddingHorizontal: 48,
    fontFamily: 'NotoSans', fontSize: 9.5, color: C.ink, lineHeight: 1.55,
  },
  brandRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 8 },
  wordmark: { fontSize: 15, fontWeight: 700, color: C.ink, lineHeight: 1.15 },
  wordmarkAI: { color: C.neem },
  tagline: { fontSize: 7.5, color: C.ink2, fontFamily: 'NotoSansDeva', lineHeight: 1.4, marginTop: 2 },
  protoChip: {
    fontSize: 7, color: C.haldiDark, backgroundColor: C.haldiLight,
    paddingHorizontal: 6, paddingVertical: 2, borderRadius: 3,
  },
  rule: { borderBottomWidth: 1.2, borderBottomColor: C.neem, marginBottom: 14 },
  h1: { fontSize: 14.5, fontWeight: 700, marginBottom: 3, lineHeight: 1.25 },
  h1Hi: { fontSize: 10.5, fontWeight: 500, color: C.ink2, fontFamily: 'NotoSansDeva', marginBottom: 10, lineHeight: 1.5 },
  h2: { fontSize: 10.5, fontWeight: 700, marginTop: 14, marginBottom: 5, color: C.neemDark },
  p: { marginBottom: 6 },
  pHi: { marginBottom: 6, fontFamily: 'NotoSansDeva' },
  small: { fontSize: 8, color: C.ink2 },
  mono: { fontFamily: 'JansahMono', letterSpacing: 0.5 },
  metaBox: {
    flexDirection: 'row', justifyContent: 'space-between', backgroundColor: C.paper1,
    borderWidth: 1, borderColor: C.line, borderRadius: 5, padding: 9, marginBottom: 12,
  },
  row: { flexDirection: 'row', marginBottom: 3 },
  rowLabel: { width: 130, color: C.ink2, fontSize: 8.6 },
  rowValue: { flex: 1, fontSize: 9.3 },
  tbl: { borderWidth: 1, borderColor: C.line, borderRadius: 4, marginVertical: 6 },
  tblHead: { flexDirection: 'row', backgroundColor: C.paper1, borderBottomWidth: 1, borderBottomColor: C.line },
  tblRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: C.line },
  tblCell: { padding: 5, fontSize: 8.6 },
  footerWrap: {
    position: 'absolute', bottom: 26, left: 48, right: 48,
    borderTopWidth: 0.8, borderTopColor: C.line, paddingTop: 6,
  },
  footer: { fontSize: 7, color: C.ink3, textAlign: 'center' },
  watermark: {
    position: 'absolute', top: 330, left: 40, right: 0,
    transform: 'rotate(-30deg)', fontSize: 84, fontWeight: 700,
    color: '#C2491F', opacity: 0.13, textAlign: 'center',
  },
  callout: {
    backgroundColor: C.haldiLight, borderRadius: 5, padding: 8, marginVertical: 8,
    fontSize: 8.6, color: C.haldiDark,
  },
  sigBlock: { marginTop: 26, flexDirection: 'row', justifyContent: 'space-between' },
  sigLine: { width: 200, borderTopWidth: 0.8, borderTopColor: C.ink2, paddingTop: 3, fontSize: 8.4, color: C.ink2 },
});

export const FOOTER_TEXT =
  'Generated by Jansah.AI — independent hackathon prototype. Not an official or government document. Demo data only.';

export function T({ children, style }: { children: React.ReactNode; style?: object | object[] }) {
  // Text that auto-selects Devanagari-capable font
  const str = React.Children.toArray(children).join('');
  return <Text style={[{ fontFamily: familyFor(str) }, ...(Array.isArray(style) ? style : style ? [style] : [])]}>{children}</Text>;
}

/** The shirorekha mark from the jansah-logo kit (mark.svg) — bar lengths fixed, bindu always present. */
export function JansahMarkPdf({ size = 26 }: { size?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 48 48">
      <Line x1={9} y1={12} x2={39} y2={12} stroke={C.neem} strokeWidth={4} strokeLinecap="round" />
      <Line x1={15} y1={12} x2={15} y2={24} stroke={C.neem} strokeWidth={4} strokeLinecap="round" />
      <Line x1={23} y1={12} x2={23} y2={34} stroke={C.neem} strokeWidth={4} strokeLinecap="round" />
      <Line x1={31} y1={12} x2={31} y2={27} stroke={C.neem} strokeWidth={4} strokeLinecap="round" />
      <Line x1={39} y1={12} x2={39} y2={38} stroke={C.neem} strokeWidth={4} strokeLinecap="round" />
      <Circle cx={44} cy={7} r={2.8} fill={C.haldi} />
    </Svg>
  );
}

export function Letterhead({ caseNumber, title, titleHi, date, virtualNote }: {
  caseNumber: string; title: string; titleHi?: string; date: string; virtualNote?: string | null;
}) {
  return (
    <View>
      <View style={s.brandRow}>
        <View style={{ flexDirection: 'row', alignItems: 'flex-start' }}>
          <View style={{ marginRight: 7, marginTop: 1 }}><JansahMarkPdf size={26} /></View>
          <View>
            <Text style={s.wordmark}>Jansah<Text style={s.wordmarkAI}>.AI</Text></Text>
            <Text style={s.tagline}>Janta ka Sahai · जनता का सहाई</Text>
          </View>
        </View>
        <View style={{ alignItems: 'flex-end' }}>
          <Text style={s.protoChip}>INDEPENDENT PROTOTYPE — NOT A GOVERNMENT SERVICE</Text>
          <Text style={[s.small, { marginTop: 3 }]}>Case <Text style={s.mono}>{formatCaseNumber(caseNumber)}</Text> · {date}{virtualNote ? `  (${virtualNote})` : ''}</Text>
        </View>
      </View>
      <View style={s.rule} />
      <Text style={s.h1}>{title}</Text>
      {titleHi ? <Text style={s.h1Hi}>{titleHi}</Text> : <View style={{ marginBottom: 8 }} />}
    </View>
  );
}

export function Footer() {
  // NOTE: react-pdf's render-prop (page numbers) silently drops text when the page
  // uses a custom registered font — plain text keeps the mandated disclaimer visible.
  return (
    <View style={s.footerWrap} fixed>
      <Text style={s.footer}>{FOOTER_TEXT}</Text>
    </View>
  );
}

export function KV({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <View style={s.row}>
      <Text style={s.rowLabel}>{label}</Text>
      <T style={[s.rowValue, ...(mono ? [s.mono] : [])]}>{value || '—'}</T>
    </View>
  );
}

export function Table({ head, widths, rows }: { head: string[]; widths: number[]; rows: string[][] }) {
  return (
    <View style={s.tbl}>
      <View style={s.tblHead}>
        {head.map((h, i) => (
          <Text key={i} style={[s.tblCell, { flex: widths[i], fontWeight: 700, fontSize: 8 }]}>{h}</Text>
        ))}
      </View>
      {rows.map((r, ri) => (
        <View key={ri} style={[s.tblRow, ...(ri === rows.length - 1 ? [{ borderBottomWidth: 0 }] : [])]}>
          {r.map((cell, ci) => <T key={ci} style={[s.tblCell, { flex: widths[ci] }]}>{cell}</T>)}
        </View>
      ))}
    </View>
  );
}

export function BasePage({ children, watermark }: { children: React.ReactNode; watermark?: string }) {
  return (
    <Page size="A4" style={s.page}>
      {watermark ? <Text style={s.watermark} fixed>{watermark}</Text> : null}
      {children}
      <Footer />
    </Page>
  );
}

export function Doc({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Document title={title} author="Jansah.AI (prototype)" creator="Jansah.AI" producer="Jansah.AI">
      {children}
    </Document>
  );
}
