import { createRequire } from 'node:module';

import { Document, Font, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer';
import React from 'react';

import type { ArtifactKind, CaseRecord } from '../domain/types.js';
import { categoryLabels } from '../engine/playbooks.js';

const require = createRequire(import.meta.url);
let fontsReady = false;
function registerFonts() {
  if (fontsReady) return;
  try {
    Font.register({ family: 'Noto', src: require.resolve('@fontsource/noto-sans-devanagari/files/noto-sans-devanagari-devanagari-400-normal.woff') });
  } catch {
    // React PDF's built-in Helvetica remains a safe English fallback in minimal installs.
  }
  fontsReady = true;
}

export const artifactLabels: Record<ArtifactKind, string> = {
  complaint_pdf: 'Cybercrime complaint', bank_notice: 'Bank dispute notice', fir_pack: 'FIR application pack',
  sp_letter: 'SP escalation letter', magistrate_draft: 'Magistrate application draft', takedown_letter: 'Platform takedown letter',
  certin_email: 'CERT-In incident email', gac_note: 'GAC appeal guide', restoration_request: 'Money restoration request',
};

const styles = StyleSheet.create({
  page: { padding: 46, fontFamily: 'Noto', fontSize: 10, lineHeight: 1.55, color: '#2c2430' },
  eyebrow: { fontSize: 8, color: '#a6483e', letterSpacing: 1.5, marginBottom: 6 },
  title: { fontSize: 22, fontWeight: 700, color: '#28152e', marginBottom: 7 },
  subtitle: { fontSize: 9, color: '#6e626b', marginBottom: 22 },
  section: { marginTop: 16, marginBottom: 7, fontSize: 11, fontWeight: 700, color: '#28152e' },
  box: { backgroundColor: '#f7f0ec', borderRadius: 8, padding: 12, marginBottom: 10 },
  row: { flexDirection: 'row', borderBottom: '1 solid #e7ddd9', paddingVertical: 6 },
  label: { width: '34%', color: '#7b7078' }, value: { width: '66%' },
  body: { marginBottom: 8 },
  hindi: { marginTop: 4, marginBottom: 8, fontFamily: 'Noto', fontSize: 10.5, lineHeight: 1.6 },
  watermark: { position: 'absolute', top: 350, left: 70, transform: 'rotate(-32deg)', fontSize: 48, color: '#ecd8d4', opacity: 0.7 },
  footer: { position: 'absolute', bottom: 24, left: 46, right: 46, borderTop: '1 solid #e7ddd9', paddingTop: 7, fontSize: 7.5, color: '#8a7d85' },
});

const Footer = () => <Text fixed style={styles.footer}>Generated by SahAI - independent hackathon prototype. Not an official or government document. Demo data only.</Text>;
const Field = ({ label, value }: { label: string; value?: unknown }) => <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value == null || value === '' ? '—' : String(value)}</Text></View>;

function Complaint({ record }: { record: CaseRecord }) {
  const txns = Array.isArray(record.slots.txns) ? record.slots.txns as Array<Record<string, unknown>> : [];
  return <>
    <Text style={styles.eyebrow}>SAHAI CASE DOCUMENT</Text><Text style={styles.title}>Cybercrime Complaint (Prototype)</Text>
    <Text style={styles.subtitle}>Citizen copy · Generated {new Date().toLocaleString('en-IN')}</Text>
    <View style={styles.box}>
      <Field label="Case number" value={record.caseNumber} /><Field label="Category" value={categoryLabels[record.category] ?? record.category} />
      <Field label="Track" value={record.track.replace('_', ' / ')} /><Field label="Status" value={record.status.replaceAll('_', ' ')} />
    </View>
    <Text style={styles.section}>Complainant</Text>
    <Field label="Name" value={record.anonymous ? 'ANONYMOUS COMPLAINT' : record.reporterName} />
    {record.onBehalfOf && <Field label="Filed for" value={record.victimName} />}
    <Field label="Contact" value={record.phoneMasked} /><Field label="Email" value={record.email} />
    <Text style={styles.section}>Incident chronology</Text><Text style={styles.body}>{String(record.slots.narrative ?? 'No narrative provided.')}</Text>
    <Field label="Incident time" value={record.incidentAt} /><Field label="Loss amount" value={record.amountLost ? `INR ${record.amountLost.toLocaleString('en-IN')}` : undefined} />
    {txns.length > 0 && <><Text style={styles.section}>Transactions</Text>{txns.map((txn, index) => <Text key={index} style={styles.body}>Transaction {index + 1} - INR {String(txn.amount ?? '-')} / {String(txn.method ?? record.slots.instrument ?? '-')} / ref {String(txn.ref ?? '-')}</Text>)}</>}
    <Text style={styles.section}>Hindi summary / हिंदी सारांश</Text><Text style={styles.hindi}>यह एक स्वतंत्र हैकाथॉन प्रोटोटाइप द्वारा बनाया गया शिकायत दस्तावेज़ है। यह सरकारी दस्तावेज़ नहीं है। केस नंबर: {record.caseNumber}।</Text>
    <Text style={styles.section}>Evidence declaration</Text><Text style={styles.body}>I state that the information above is true to my knowledge. I understand this prototype document is for demonstration and personal record.</Text>
    <Text style={styles.body}>Signature: ____________________     Date: ____________________</Text><Footer />
  </>;
}

function Letter({ record, kind }: { record: CaseRecord; kind: ArtifactKind }) {
  const days = record.timeOffsetDays;
  const text: Record<Exclude<ArtifactKind, 'complaint_pdf'>, { to: string; subject: string; body: string[] }> = {
    bank_notice: { to: `The Branch Manager / Nodal Officer, ${String(record.slots.own_bank ?? 'Bank')}`, subject: 'Dispute of unauthorised electronic transactions — request under RBI limited-liability framework', body: [
      `I report the fraudulent or unauthorised transactions described in SahAI case ${record.caseNumber}. The total amount reported is INR ${Number(record.amountLost ?? 0).toLocaleString('en-IN')}.`,
      'I request immediate blocking of further debits, registration of this dispute with written acknowledgment, a recall or hold request to the beneficiary bank, and written status within 10 working days.',
      'This draft references the RBI customer-protection framework dated 06.07.2017 and successors. Please review, sign, and send it yourself through the bank’s official channel.',
    ]},
    fir_pack: { to: 'The Station House Officer, jurisdictional Cyber Crime / local Police Station', subject: 'Request to register FIR — cognizable offence(s) disclosed', body: [
      `I filed cybercrime complaint ${record.caseNumber}. ${days || 15} days have passed without an FIR being recorded in this prototype case.`,
      'The annexed facts disclose potential cognizable offences. I request registration of an FIR, a free copy, and acknowledgment of this application. The principle in Lalita Kumari v. State of U.P. requires registration where cognizable information is disclosed.',
      'Annexures: complaint copy; transaction and identifier details; evidence list; electronic-record certificate block under BSA 2023 s.63.',
      'Electronic-record certificate: I produced the listed electronic records from the device/account ordinarily used by me. Device/account: __________  Produced by: __________  Signature: __________',
    ]},
    sp_letter: { to: 'The Superintendent of Police, District', subject: 'Application regarding non-registration of FIR under BNSS s.173(4)', body: [
      `I submitted a written complaint and SHO application regarding case ${record.caseNumber}, but no FIR is recorded. I request action under BNSS s.173(4) (CrPC s.154(3) equivalent).`,
      'Please investigate or direct registration and provide a written acknowledgment. The complaint and SHO application are annexed.',
    ]},
    magistrate_draft: { to: 'Before the Court of the Jurisdictional Magistrate', subject: 'DRAFT application under BNSS s.175(3)', body: [
      `The applicant filed complaint ${record.caseNumber}, followed by written applications to the SHO and Superintendent of Police. No FIR is recorded in this prototype case.`,
      'The applicant respectfully seeks a direction to police to register and investigate. This is a template only; have a lawyer review it before filing.',
    ]},
    takedown_letter: { to: `The Grievance Officer, ${String((record.slots.platforms as string[] | undefined)?.join(', ') ?? 'Platform')}`, subject: 'Complaint under IT Rules 2021 — urgent removal request', body: [
      `The content listed in case ${record.caseNumber} is reported as non-consensual intimate imagery, harassment, or impersonation. I request urgent removal, account action, acknowledgment, and preservation of records for law enforcement.`,
      `URLs/handles: ${String((record.slots.urls as string[] | undefined)?.join(', ') ?? (record.slots.suspect_handles as string[] | undefined)?.join(', ') ?? 'See complaint')}`,
      'This draft is for the citizen to send through the platform’s published grievance channel. SahAI does not contact the platform.',
    ]},
    certin_email: { to: 'incident@cert-in.org.in (send from your own mailbox)', subject: `Cyber incident report — case ${record.caseNumber}`, body: [
      `Incident type: ${categoryLabels[record.category] ?? record.category}. Affected system/account: ${String(record.slots.system_affected ?? record.slots.account_id ?? '—')}.`,
      `Timeline: ${String(record.slots.narrative ?? '—')}`, 'Actions taken: ____________________  Contact for follow-up: ____________________',
    ]},
    gac_note: { to: 'Citizen guidance note', subject: 'Grievance Appellate Committee appeal checklist', body: [
      'If the platform grievance is unresolved after the applicable period, prepare an appeal with the takedown letter, proof of sending, platform response, and current proof that content remains available.',
      'Use only the official GAC channel. This prototype does not file the appeal.',
    ]},
    restoration_request: { to: 'Money Restoration / legal-services channel', subject: 'Request for restoration of held funds', body: [
      `Case number: ${record.caseNumber}. Amount shown as held: INR ${Number(record.slots.amount_held ?? 0).toLocaleString('en-IN')}.`,
      'I request restoration to the source account. Where a court order is required, I request guidance through the DLSA or Lok Adalat route.',
    ]},
  };
  const content = text[kind as Exclude<ArtifactKind, 'complaint_pdf'>];
  return <>
    {kind === 'magistrate_draft' && <Text style={styles.watermark}>DRAFT · LAWYER REVIEW</Text>}
    <Text style={styles.eyebrow}>SAHAI READY-TO-SEND DRAFT</Text><Text style={styles.title}>{artifactLabels[kind]}</Text>
    <Text style={styles.subtitle}>Case {record.caseNumber}</Text><Field label="To" value={content.to} /><Field label="Subject" value={content.subject} />
    <Text style={styles.section}>Sir / Madam,</Text>{content.body.map((paragraph, index) => <Text key={index} style={styles.body}>{paragraph}</Text>)}
    <Text style={styles.body}>Sincerely,</Text><Text style={styles.body}>{record.anonymous ? `Case ${record.caseNumber}` : record.reporterName ?? 'Complainant'}</Text>
    <Text style={styles.body}>Signature: ____________________     Date: ____________________</Text><Footer />
  </>;
}

export async function renderArtifact(record: CaseRecord, kind: ArtifactKind): Promise<Buffer> {
  registerFonts();
  const document = <Document><Page size="A4" style={styles.page}>{kind === 'complaint_pdf' ? <Complaint record={record} /> : <Letter record={record} kind={kind} />}</Page></Document>;
  const blob = await pdf(document).toBlob();
  return Buffer.from(await blob.arrayBuffer());
}
